enter_username_locator = By.ID, 'mat-input-0'
enter_password_locator = By.ID, 'mat-input-1'
click_on_login_locator = By.ID, 'Login-btn'
click_on_edit_profile = By.XPATH, '//p[text()="Hi Sakshi"]/../..//span[@class="caret colorWhite"]'
click_on_update_profile = By.XPATH, '//li//a[text()="Update Profile"]'
click_on_cancel = By.XPATH, '//button[@class="landingbutton buttonNew md-button md-ink-ripple"]'
click_on_login_settings = By.XPATH, '//span[text()="Login Settings"]'
login_locator = By.ID, '//button[@class="whiteButton ml-15"]'
clicking_on_change_email = By.XPATH, '//span[text()="Change Email"]'
enter_email = By.XPATH, '//input[@id="newEmail"]'
confirm_email = By.XPATH, '//input[@name="cnfemail"]'
enter_password = By.XPATH, '//input[@name="password"]'
submit_button = By.XPATH, '//md-input-container//span[text()="Submit"]'
clicking_on_verify_your_email = By.XPATH, '//button[text()="Verify your email "]'
entering_mail = By.XPATH, '//input[@class="ycptinput"]'
arrow_locator = By.XPATH, '//i[@class="material-icons-outlined f36"]'
netgear_locator = By.XPATH, '//span[text()="NETGEAR"]/../../..//input'
here_locator = By.XPATH, '//a[text()="here"]'
back_arrow_locator = By.XPATH, '//a[@class="back-button buttonPosition btnPosAccount"]'
done_locator = By.XPATH, '//span[text()="Done"]'
double_verify = By.XPATH, "//a[text()='Click here to verify your email.']"
resend_email = By.XPATH, '//span[text()="Resend email"]'
refresh_locator = By.ID, 'refresh'
clicking_on_cancel_button = By.XPATH, '//span[text()="Cancel"]'
change_password_button = By.XPATH, '//span[text()="Change Password"]'
input_old_password = By.XPATH, '//input[@name="cPassword"]'
input_new_password = By.XPATH, '//input[@name="nPassword"]'
input_confirm_new_password = By.XPATH, '//input[@name="cnPassword"]'
submit_locator = By.XPATH, '//button[@name="changePasswordButton"]//span[text()="Submit"]'
two_step_verification_locator = By.XPATH, '//span[text()="Two-Step Verification"]'
enable_locator = By.XPATH, '//div[@class="mdc-switch__shadow"]'
selecting_country_numbers = By.XPATH, '//div[@class="selected-flag"]'
france_locator = By.XPATH, '//span[text()="France"]'
input_number = By.XPATH, '//input[@name="tel"]'
number_selector = By.XPATH, '//strong[text()="SMS Text Message"]/../..//span'
continue_selector = By.XPATH, '//button[text()="Continue"]'